name: Generate Data

on:
  schedule: # executa a cada 12 horas
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Job to update data
    runs-on: ubuntu-latest
    steps:
      - uses: platane/snk@master
        id: snake-gif
        with:
          github_user_name: BrunoRodrigo23
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
